### ISSUE TITLE
Looking forward to this

### ISSUE THREAD

**Issue by tux7k** [KoopaCruiser/KoopaCruiser#2]
Even after the 3DS Discontinued I am still looking forward and a basic HTML Web Browser would be cool.

**Comment by thatsprettygood** [comment]
![image](https://user-images.githubusercontent.com/36249601/106964618-5fd71180-6710-11eb-9b23-7d9c2418f1f3.png)

**Comment by tuckotb** [comment]
yes i know, thats why im asking
